"""add order_index to songs

Revision ID: 1b105e6cc9be
Revises: 67fe0c86c01c
Create Date: 2026-07-25 22:37:03.141526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b105e6cc9be'
down_revision: Union[str, Sequence[str], None] = '67fe0c86c01c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('order_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'order_index')
    # ### end Alembic commands ###
