"""add gig_id to attendance, make rehearsal_plan_id nullable

Revision ID: 36906bfad440
Revises: 320b63d787da
Create Date: 2026-08-06 02:45:34.059974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36906bfad440'
down_revision: Union[str, Sequence[str], None] = '320b63d787da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance', 'rehearsal_plan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('uk_attendance_member_gig'), 'attendance', type_='unique')
    op.create_unique_constraint('uq_attendance_gig_member', 'attendance', ['gig_id', 'member_id'])
    op.create_foreign_key(None, 'attendance', 'gigs', ['gig_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_constraint('uq_attendance_gig_member', 'attendance', type_='unique')
    op.create_unique_constraint(op.f('uk_attendance_member_gig'), 'attendance', ['member_id', 'gig_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('attendance', 'rehearsal_plan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
