"""create rehearsal_plans and rehearsal_plan_items tables

Revision ID: 67fe0c86c01c
Revises: fde3d9e7654c
Create Date: 2026-07-21 23:37:08.484026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67fe0c86c01c'
down_revision: Union[str, Sequence[str], None] = 'fde3d9e7654c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rehearsal_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rehearsal_plans_id'), 'rehearsal_plans', ['id'], unique=False)
    op.create_table('rehearsal_plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rehearsal_plan_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rehearsal_plan_id'], ['rehearsal_plans.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rehearsal_plan_items_id'), 'rehearsal_plan_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rehearsal_plan_items_id'), table_name='rehearsal_plan_items')
    op.drop_table('rehearsal_plan_items')
    op.drop_index(op.f('ix_rehearsal_plans_id'), table_name='rehearsal_plans')
    op.drop_table('rehearsal_plans')
    # ### end Alembic commands ###
