"""add start_time and end_time to rehearsal_plans

Revision ID: 73b02c8bd218
Revises: 1b105e6cc9be
Create Date: 2026-07-27 11:03:41.378158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b02c8bd218'
down_revision: Union[str, Sequence[str], None] = '1b105e6cc9be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rehearsal_plans', sa.Column('start_time', sa.String(), nullable=True))
    op.add_column('rehearsal_plans', sa.Column('end_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rehearsal_plans', 'end_time')
    op.drop_column('rehearsal_plans', 'start_time')
    # ### end Alembic commands ###
