"""create gigs table

Revision ID: 77641c6417a0
Revises: d5ae0493576a
Create Date: 2026-08-03 10:14:14.469223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77641c6417a0'
down_revision: Union[str, Sequence[str], None] = 'd5ae0493576a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gigs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('performance_time', sa.String(), nullable=True),
    sa.Column('costume', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gigs_id'), 'gigs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gigs_id'), table_name='gigs')
    op.drop_table('gigs')
    # ### end Alembic commands ###
